/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { AccessibilityIssue } from '../models/Issue';
import { checkHyperlink } from '../checks/HyperlinkCheck';
import { generateAiAltText, generateAiLinkTitle, detectMimeFromBytes, getInlineImageMapViaRest } from '../utils/AiUtil';
import { getContrastRatio } from '../utils/ColorUtil';

/**
 * Helper function to force Google Apps Script OAuth consent dialog when run from Apps Script Editor.
 */
export function forceReauthorizeScopes(): string {
  console.log('[forceReauthorizeScopes] Triggering UrlFetchApp for Google Cloud OAuth scope consent...');
  const token = ScriptApp.getOAuthToken();
  const res = UrlFetchApp.fetch(`https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=${token}`, {
    muteHttpExceptions: true
  });
  console.log('[forceReauthorizeScopes] TokenInfo response code:', res.getResponseCode());
  console.log('[forceReauthorizeScopes] TokenInfo response body:', res.getContentText());
  return `OAuth Scopes Authorized Successfully! Response Code: ${res.getResponseCode()}`;
}

/**
 * Evaluates whether an alternative text string is missing, empty, or a generic filename/default label.
 */
function isGenericOrInvalidAltText(alt: string | null): { invalid: boolean; reason: string } {
  if (alt === null) {
    return { invalid: true, reason: 'missing alternative text attribute (alt)' };
  }
  const trimmed = alt.trim();
  if (trimmed === '') {
    return { invalid: true, reason: 'empty alternative text (alt="")' };
  }
  if (/^visual photograph or graphic attachment/i.test(trimmed) || /^attached visual email graphic/i.test(trimmed) || /^descriptive email graphic/i.test(trimmed)) {
    return { invalid: true, reason: 'generic placeholder alternative text' };
  }
  // Check for filenames or generic default labels auto-generated by Gmail/mail clients
  const genericPatterns = [
    /^image(\.\w+)?$/i,
    /^screenshot(\s+|-|\d|_|at|\.)*$/i,
    /^photo(\s+|-|\d|_|\.)*$/i,
    /^picture(\s+|-|\d|_|\.)*$/i,
    /^pasted\s+image/i,
    /^img(\s+|-|\d|_|\.)*$/i,
    /^\w+[-_]\w+\.(png|jpg|jpeg|gif|webp|bmp|svg)$/i,
    /\.(png|jpg|jpeg|gif|webp|bmp|svg)$/i,
    /^untitled/i,
    /^default/i,
    /^graphic$/i,
    /^attachment$/i,
  ];

  for (const pattern of genericPatterns) {
    if (pattern.test(trimmed)) {
      return { invalid: true, reason: `generic filename or default label ("${trimmed}")` };
    }
  }

  return { invalid: false, reason: '' };
}

/**
 * Parses Gmail compose draft HTML body and runs pre-send WCAG 2.1 AA checks.
 */
export function auditGmailDraftHtml(htmlContent: string, inlineBlobs?: GoogleAppsScript.Base.Blob[]): AccessibilityIssue[] {
  const issues: AccessibilityIssue[] = [];
  if (!htmlContent) return issues;

  // 1. Scan <a> links in draft HTML for WCAG 2.4.4 Link Purpose
  const linkRegex = /<a\s+[^>]*href=["']([^"']+)["'][^>]*>(.*?)<\/a>/gi;
  let match: RegExpExecArray | null;
  let linkIdx = 0;

  while ((match = linkRegex.exec(htmlContent)) !== null) {
    linkIdx++;
    const url = match[1];
    const rawAnchor = match[2].replace(/<[^>]+>/g, '').trim();

    if (rawAnchor) {
      const issue = checkHyperlink(`gmail_link_${linkIdx}`, 'Email Link', rawAnchor, url);
      if (issue) {
        issue.canAutoFix = true;
        const domain = url.replace(/^https?:\/\//i, '').split('/')[0] || 'destination link';
        let aiLinkText = '';
        try {
          aiLinkText = generateAiLinkTitle(rawAnchor, htmlContent, url);
        } catch (e) {}
        (issue as any).url = url;
        (issue as any).rawAnchor = rawAnchor;
        (issue as any).suggestedText = aiLinkText || `${rawAnchor} (${domain})`;
        issues.push(issue);
      }
    }
  }

  // 2. Scan <img> tags in draft HTML for WCAG 1.1.1 Image Alt Text
  const imgRegex = /<img\b([^>]*)>/gi;
  let imgIdx = 0;

  console.log(`[DEBUG_IMAGE_DIAGNOSTIC] Scanning HTML body for <img> tags. inlineBlobs count: ${inlineBlobs ? inlineBlobs.length : 0}`);
  while ((match = imgRegex.exec(htmlContent)) !== null) {
    imgIdx++;
    const fullImgTag = match[0];
    const attributes = match[1];
    const altMatch = /alt=(?:["']([^"']*)["']|([^\s>]+))/i.exec(attributes);
    const srcMatch = /src=(?:["']([^"']*)["']|([^\s>]+))/i.exec(attributes);
    const altText = altMatch ? (altMatch[1] !== undefined ? altMatch[1].trim() : altMatch[2].trim()) : null;
    const srcAttr = srcMatch ? (srcMatch[1] !== undefined ? srcMatch[1].trim() : srcMatch[2].trim()) : '(none)';
    const altCheck = isGenericOrInvalidAltText(altText);

    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] Image #${imgIdx}: tag="${fullImgTag.substring(0, 100)}...", src="${srcAttr}", alt="${altText}", invalid=${altCheck.invalid}`);

    if (altCheck.invalid) {
      issues.push({
        elementId: `gmail_img_${imgIdx}`,
        elementType: 'Inline Email Image',
        issueType: 'Alternative Text',
        severity: 'ERROR',
        wcagRule: 'WCAG 1.1.1 Non-text Content',
        title: `Missing or Generic Alternative Text (Inline Image #${imgIdx})`,
        description: `Inline image has ${altCheck.reason}. Recipients using screen readers cannot perceive visual attachments without descriptive alternative text explaining what the image shows.`,
        snippet: `Inline Image #${imgIdx}`,
        canAutoFix: true,
        imgIdx: imgIdx,
        suggestedAlt: '',
      });
    }
  }

  // 3. Scan for simulated manual lists in draft HTML (not in <ul> or <ol>)
  const blockListRegex = /<(div|p|span|td|th|blockquote|li)[^>]*>\s*([*•▪▫►❖➢·⁃\u2013\u2014]|[-+](?=\s)|(o|O)(?=\s)|\d+[\.\)]|[a-zA-Z][\.\)]|\([0-9a-zA-Z]\))\s+([^<]+?)\s*<\/\1>/gi;
  let listMatch: RegExpExecArray | null;
  let listIdx = 0;
  while ((listMatch = blockListRegex.exec(htmlContent)) !== null) {
    listIdx++;
    const fullMatch = listMatch[0];
    const marker = listMatch[2];
    const itemText = listMatch[4].trim();
    if (itemText && !/^\d+$/.test(itemText)) {
      issues.push({
        elementId: `gmail_list_${listIdx}`,
        elementType: 'Email Text',
        issueType: 'List Formatting',
        severity: 'NOTICE',
        wcagRule: 'WCAG 1.3.1 Info and Relationships',
        title: `Simulated list item using manual characters ("${marker}...")`,
        description: 'Screen readers do not announce manual symbols as list items. Use native email bullet or numbered list formatting.',
        snippet: `${marker} ${itemText.substring(0, 40)}`,
        canAutoFix: true,
        oldText: fullMatch,
        newText: `<ul><li>${itemText}</li></ul>`,
      });
    }
  }

  // Also catch line-break or text separated simulated lists not inside simple block tags
  const brListRegex = /(?:<br\s*\/?>|^\s*)\s*([*•▪▫►❖➢·⁃\u2013\u2014]|[-+](?=\s)|(o|O)(?=\s)|\d+[\.\)]|[a-zA-Z][\.\)]|\([0-9a-zA-Z]\))\s+([^<]+?)(?=(?:<br\s*\/?>|<|$))/gi;
  while ((listMatch = brListRegex.exec(htmlContent)) !== null) {
    const fullMatch = listMatch[0];
    if (!issues.some(i => i.oldText === fullMatch)) {
      listIdx++;
      const marker = listMatch[1];
      const itemText = listMatch[3].trim();
      if (itemText && !/^\d+$/.test(itemText)) {
        issues.push({
          elementId: `gmail_list_${listIdx}`,
          elementType: 'Email Text',
          issueType: 'List Formatting',
          severity: 'NOTICE',
          wcagRule: 'WCAG 1.3.1 Info and Relationships',
          title: `Simulated list item using manual characters ("${marker}...")`,
          description: 'Screen readers do not announce manual symbols as list items. Use native email bullet or numbered list formatting.',
          snippet: `${marker} ${itemText.substring(0, 40)}`,
          canAutoFix: true,
          oldText: fullMatch,
          newText: `<ul><li>${itemText}</li></ul>`,
        });
      }
    }
  }

  // 4. Scan for low color contrast text in email draft
  const colorRegex = /<(?:div|p|span|td|th|li|a|b|i|font)[^>]*style=["'][^"']*color:\s*(#[0-9a-fA-F]{3,6}|rgb\([^)]+\))[^"']*["'][^>]*>([\s\S]+?)<\/(?:div|p|span|td|th|li|a|b|i|font)>/gi;
  let colorMatch: RegExpExecArray | null;
  let contrastIdx = 0;
  while ((colorMatch = colorRegex.exec(htmlContent)) !== null) {
    const fullMatch = colorMatch[0];
    const colorVal = colorMatch[1];
    const textContent = colorMatch[2].replace(/<[^>]+>/g, '').trim();
    if (textContent && !issues.some(i => i.oldText === fullMatch)) {
      let hex = '';
      if (colorVal.startsWith('#')) {
        let c = colorVal.replace('#', '').trim();
        if (c.length === 3) c = c.split('').map(x => x + x).join('');
        hex = `#${c.toUpperCase()}`;
      } else {
        const rgbM = /rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i.exec(colorVal);
        if (rgbM) {
          const toHex = (n: number) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, '0');
          hex = `#${toHex(parseInt(rgbM[1], 10))}${toHex(parseInt(rgbM[2], 10))}${toHex(parseInt(rgbM[3], 10))}`.toUpperCase();
        }
      }
      if (hex) {
        try {
          const ratio = getContrastRatio(hex, '#FFFFFF');
          if (ratio < 4.5) {
            contrastIdx++;
            issues.push({
              elementId: `gmail_contrast_${contrastIdx}`,
              elementType: 'Email Text',
              issueType: 'Color Contrast',
              severity: 'ERROR',
              wcagRule: 'WCAG 1.4.3 Contrast (Minimum)',
              title: `Low Color Contrast (${ratio}:1 against white)`,
              description: `Text color (${hex}) does not meet the 4.5:1 minimum contrast ratio against a white background, making it difficult for vision-impaired users to read.`,
              snippet: textContent.substring(0, 40),
              canAutoFix: true,
              oldText: fullMatch,
              newText: fullMatch.replace(/color:\s*(?:#[0-9a-fA-F]{3,6}|rgb\([^)]+\))/i, 'color: #202124'),
            });
          }
        } catch (e) {}
      }
    }
  }

  // 5. Scan for non-semantic faux headings (large bold text in general container tags)
  const fauxHeadingRegex = /<(?:div|p|span)[^>]*style=["'][^"']*(?:font-size:\s*(?:1[6-9]|[2-9]\d)px[^"']*font-weight:\s*(?:bold|700|800|900)|font-weight:\s*(?:bold|700|800|900)[^"']*font-size:\s*(?:1[6-9]|[2-9]\d)px)[^"']*["'][^>]*>([\s\S]+?)<\/(?:div|p|span)>/gi;
  let fauxMatch: RegExpExecArray | null;
  let fauxIdx = 0;
  while ((fauxMatch = fauxHeadingRegex.exec(htmlContent)) !== null) {
    const fullMatch = fauxMatch[0];
    const textContent = fauxMatch[1].replace(/<[^>]+>/g, '').trim();
    if (textContent && !issues.some(i => i.oldText === fullMatch)) {
      fauxIdx++;
      issues.push({
        elementId: `gmail_heading_${fauxIdx}`,
        elementType: 'Email Heading',
        issueType: 'Heading Structure',
        severity: 'NOTICE',
        wcagRule: 'WCAG 1.3.1 Info and Relationships',
        title: `Non-Semantic Faux Heading ("${textContent.substring(0, 25)}...")`,
        description: 'Large bold text is visually styled like a heading but uses a general container tag (div/p/span). Screen readers cannot navigate to it by heading ranks.',
        snippet: textContent.substring(0, 40),
        canAutoFix: true,
        oldText: fullMatch,
        newText: `<h2 style="font-size: 16px; font-weight: bold; color: #1a73e8; margin: 12px 0;">${textContent}</h2>`,
      });
    }
  }

  // 6. Scan for data tables missing header cells (<th>)
  const tableRegex = /<table\b[^>]*>([\s\S]+?)<\/table>/gi;
  let tableMatch: RegExpExecArray | null;
  let tableIdx = 0;
  while ((tableMatch = tableRegex.exec(htmlContent)) !== null) {
    const fullMatch = tableMatch[0];
    const tableInner = tableMatch[1];
    if (!/<th\b/i.test(tableInner) && !/role=["'](?:columnheader|rowheader)["']/i.test(tableInner) && /<td\b/i.test(tableInner) && !issues.some(i => i.oldText === fullMatch)) {
      tableIdx++;
      issues.push({
        elementId: `gmail_table_${tableIdx}`,
        elementType: 'Email Table',
        issueType: 'Table Structure',
        severity: 'ERROR',
        wcagRule: 'WCAG 1.3.1 Info and Relationships',
        title: `Data Table Missing Headers (Table #${tableIdx})`,
        description: 'Table has data cells (<td>) but no header cells (<th>). Screen readers cannot associate data cells with column or row headers.',
        snippet: 'Table without <th> header cells',
        canAutoFix: true,
        oldText: fullMatch,
        newText: fullMatch.replace(/<tr\b([^>]*)>([\s\S]+?)<\/tr>/i, (trMatch, trAttrs, rowInner) => {
          const updatedRow = rowInner.replace(/<td\b([^>]*)>([\s\S]+?)<\/td>/gi, '<th style="background-color: #f1f3f4; font-weight: bold; text-align: left; padding: 6px;" $1>$2</th>');
          return `<tr ${trAttrs}>${updatedRow}</tr>`;
        }),
      });
    }
  }

  // 7. Scan for small/unreadable typography (font-size below 11px or size="1")
  const typoRegex = /<(?:div|p|span|td|li|font)[^>]*(?:style=["'][^"']*font-size:\s*(?:[1-9]|10)px[^"']*["']|size=["']1["'])[^>]*>([\s\S]+?)<\/(?:div|p|span|td|li|font)>/gi;
  let typoMatch: RegExpExecArray | null;
  let typoIdx = 0;
  while ((typoMatch = typoRegex.exec(htmlContent)) !== null) {
    const fullMatch = typoMatch[0];
    const textContent = typoMatch[1].replace(/<[^>]+>/g, '').trim();
    if (textContent && !issues.some(i => i.oldText === fullMatch)) {
      typoIdx++;
      issues.push({
        elementId: `gmail_typo_${typoIdx}`,
        elementType: 'Email Text',
        issueType: 'Readable Typography',
        severity: 'NOTICE',
        wcagRule: 'WCAG 1.4.4 Resize Text',
        title: `Small Unreadable Typography (${textContent.substring(0, 20)}...)`,
        description: 'Text formatted below 11px is difficult to read for users with low vision and violates readable typography size guidelines.',
        snippet: textContent.substring(0, 40),
        canAutoFix: true,
        oldText: fullMatch,
        newText: fullMatch.replace(/font-size:\s*([1-9]|10)px/i, 'font-size: 12px').replace(/size=["']1["']/i, 'size="2"'),
      });
    }
  }

  return issues;
}

/**
 * Helper to retrieve draft HTML body and subject from event object or latest active draft in Gmail.
 */
function resolveDraftContent(e: any, allowFallback = false): { htmlBody: string; subject: string; draftId: string; inlineBlobs?: GoogleAppsScript.Base.Blob[] } {
  let htmlBody = '';
  let subject = '';
  let inlineBlobs: GoogleAppsScript.Base.Blob[] = [];

  const draftId = e?.gmail?.draftMetadata?.id || e?.gmail?.draftId || e?.draftMetadata?.id || e?.draftMetadata?.draftId || e?.draftId || e?.gmail?.id || e?.id || '';
  console.log('[resolveDraftContent] Attempting draft resolution. DraftId from event:', draftId || '(none)');

  if (draftId && typeof GmailApp !== 'undefined') {
    try {
      const draft = GmailApp.getDraft(draftId);
      if (draft) {
        const msg = draft.getMessage();
        htmlBody = msg.getBody();
        subject = msg.getSubject() || '(Untitled Draft)';
        try {
          const cidMap = getInlineImageMapViaRest(msg.getId(), e?.gmail?.accessToken);
          const orderedBlobs: GoogleAppsScript.Base.Blob[] = [];
          const imgRegex = /<img\b[^>]*src=["']?cid:([^"'\s>]+)["']?[^>]*>/gi;
          let m: RegExpExecArray | null;
          while ((m = imgRegex.exec(htmlBody)) !== null) {
            const cid = m[1].trim();
            if (cidMap[cid]) orderedBlobs.push(cidMap[cid]);
          }
          if (orderedBlobs.length > 0) {
            inlineBlobs = orderedBlobs;
          } else {
            inlineBlobs = Object.values(cidMap);
            if (inlineBlobs.length === 0) {
              const allAtts = msg.getAttachments({ includeInlineImages: true, includeAttachments: true }) || [];
              inlineBlobs = allAtts.filter(b => b && (b.getContentType()?.toLowerCase().startsWith('image/') || /\.(jpg|jpeg|png|gif|bmp|webp|svg)$/i.test(b.getName())));
            }
          }
        } catch (e) {}
        console.log(`[resolveDraftContent] Loaded via ID (${draftId}). Body length: ${htmlBody.length}`);
      }
    } catch (err: any) {
      console.warn(`[resolveDraftContent] Error calling getDraft("${draftId}"):`, err);
    }
  }

  if (!htmlBody && allowFallback && typeof GmailApp !== 'undefined') {
    try {
      const drafts = GmailApp.getDrafts();
      console.log(`[resolveDraftContent] allowFallback=true. getDrafts() returned ${drafts ? drafts.length : 0} drafts.`);
      if (drafts && drafts.length > 0) {
        const latestDraft = drafts[0];
        const msg = latestDraft.getMessage();
        htmlBody = msg.getBody();
        subject = msg.getSubject() || '(Untitled Draft)';
        try {
          const cidMap = getInlineImageMapViaRest(msg.getId(), e?.gmail?.accessToken);
          const orderedBlobs: GoogleAppsScript.Base.Blob[] = [];
          const imgRegex = /<img\b[^>]*src=["']?cid:([^"'\s>]+)["']?[^>]*>/gi;
          let m: RegExpExecArray | null;
          while ((m = imgRegex.exec(htmlBody)) !== null) {
            const cid = m[1].trim();
            if (cidMap[cid]) orderedBlobs.push(cidMap[cid]);
          }
          if (orderedBlobs.length > 0) {
            inlineBlobs = orderedBlobs;
          } else {
            inlineBlobs = Object.values(cidMap);
            if (inlineBlobs.length === 0) {
              const allAtts = msg.getAttachments({ includeInlineImages: true, includeAttachments: true }) || [];
              inlineBlobs = allAtts.filter(b => b && (b.getContentType()?.toLowerCase().startsWith('image/') || /\.(jpg|jpeg|png|gif|bmp|webp|svg)$/i.test(b.getName())));
            }
          }
        } catch (e) {}
        console.log(`[resolveDraftContent] Loaded via getDrafts()[0] (ID: ${latestDraft.getId()}). Body length: ${htmlBody.length}`);
        return { htmlBody, subject, draftId: latestDraft.getId(), inlineBlobs };
      }
    } catch (err: any) {
      console.warn('[resolveDraftContent] Error calling getDrafts():', err);
    }
  }

  return { htmlBody, subject, draftId, inlineBlobs };
}

/**
 * Helper to render issues with 1-click Quick Fix auto-remediation buttons on Gmail cards.
 */
function renderIssuesWithQuickFix(section: GoogleAppsScript.Card_Service.CardSection, issues: AccessibilityIssue[], draftId: string, source: 'COMPOSE' | 'HOMEPAGE') {
  const fixableIssues = issues.filter(i => i.canAutoFix);
  if (fixableIssues.length > 1) {
    const fixAllAction = CardService.newAction()
      .setFunctionName('rpcApplyAllGmailFixes')
      .setParameters({
        draftId: draftId || '',
        source: source,
      });

    section.addWidget(
      CardService.newTextButton()
        .setText(`⚡ Fix All (${fixableIssues.length} Issues)`)
        .setOnClickAction(fixAllAction)
        .setTextButtonStyle(CardService.TextButtonStyle.FILLED)
    );
  }

  issues.forEach((issue: any) => {
    const keyText = `<b>${issue.severity}</b>: ${issue.title}<br><i>${issue.description}</i>`;
    section.addWidget(CardService.newTextParagraph().setText(keyText));

    if (issue.canAutoFix) {
      let fixType = 'LINK';
      let buttonText = `✨ Quick Fix: Rename Link ("${issue.suggestedText}")`;

      if (issue.issueType === 'Alternative Text') {
        fixType = 'ALT_TEXT';
        buttonText = issue.suggestedAlt ? `✨ Quick Fix: Add Alt Text ("${issue.suggestedAlt}")` : `✨ Generate & Apply AI Alt Text`;

        // 1. AI Generation Button
        const fixAction = CardService.newAction()
          .setFunctionName('rpcApplyGmailFix')
          .setParameters({
            issueId: issue.elementId || '',
            fixType: fixType,
            draftId: draftId || '',
            imgIdx: String(issue.imgIdx || 1),
            suggestedAlt: issue.suggestedAlt || '',
            source: source,
          });

        section.addWidget(
          CardService.newTextButton()
            .setText(buttonText)
            .setOnClickAction(fixAction)
        );

        // 2. Custom User Alt Text Input Field & Save Button
        const inputFieldName = `customAlt_${issue.imgIdx || 1}`;
        const customInput = CardService.newTextInput()
          .setFieldName(inputFieldName)
          .setTitle(`Custom Alt Text (Image #${issue.imgIdx || 1})`)
          .setHint('Type descriptive alternative text...');

        const customAltAction = CardService.newAction()
          .setFunctionName('rpcApplyGmailFix')
          .setParameters({
            issueId: issue.elementId || '',
            fixType: 'CUSTOM_ALT_TEXT',
            draftId: draftId || '',
            imgIdx: String(issue.imgIdx || 1),
            source: source,
          });

        section.addWidget(customInput);
        section.addWidget(
          CardService.newTextButton()
            .setText(`✍️ Save Custom Alt Text`)
            .setOnClickAction(customAltAction)
        );

        // 3. Mark as Decorative Button
        const decorativeAction = CardService.newAction()
          .setFunctionName('rpcApplyGmailFix')
          .setParameters({
            issueId: issue.elementId || '',
            fixType: 'MARK_DECORATIVE',
            draftId: draftId || '',
            imgIdx: String(issue.imgIdx || 1),
            source: source,
          });

        section.addWidget(
          CardService.newTextButton()
            .setText(`🎨 Mark Image as Decorative (alt="")`)
            .setOnClickAction(decorativeAction)
        );
      } else {
        if (issue.issueType === 'List Formatting') {
          fixType = 'LIST';
          buttonText = `✨ Quick Fix: Convert to Bullet List`;
        }

        const fixAction = CardService.newAction()
          .setFunctionName('rpcApplyGmailFix')
          .setParameters({
            issueId: issue.elementId || '',
            fixType: fixType,
            draftId: draftId || '',
            url: issue.url || '',
            oldText: issue.rawAnchor || issue.oldText || '',
            newText: issue.suggestedText || issue.newText || '',
            imgIdx: String(issue.imgIdx || 1),
            suggestedAlt: issue.suggestedAlt || '',
            source: source,
          });

        section.addWidget(
          CardService.newTextButton()
            .setText(buttonText)
            .setOnClickAction(fixAction)
        );
      }
    }
  });
}

/**
 * Applies 1-click quick fixes (link renaming or alt text insertion) directly into the Gmail compose draft HTML body.
 * Logs all execution steps to Stackdriver / Cloud Console to assist debugging.
 */
export function rpcApplyGmailFix(e: any): any {
  console.log('[rpcApplyGmailFix] START. Triggered with event parameters:', JSON.stringify(e?.parameters || {}));

  const fixType = e?.parameters?.fixType;
  let draftId = e?.parameters?.draftId;
  const source = e?.parameters?.source || 'COMPOSE';

  let { htmlBody, subject, draftId: resolvedId, inlineBlobs } = resolveDraftContent(e, true);
  if (!draftId) draftId = resolvedId;

  console.log(`[rpcApplyGmailFix] Retrieved initial HTML body. Length: ${htmlBody.length} bytes.`);
  console.log('[rpcApplyGmailFix] Initial HTML snippet:', htmlBody.substring(0, 500));

  let updatedHtml = htmlBody;

  if (fixType === 'LINK') {
    const oldUrl = e.parameters['url'] || '';
    const oldText = e.parameters['oldText'] || '';
    const newText = e.parameters['newText'] || `${oldText} (descriptive link)`;

    console.log(`[rpcApplyGmailFix] LINK fix requested. Target URL: "${oldUrl}", Target Text: "${oldText}", Replacement: "${newText}"`);

    let matchCount = 0;
    updatedHtml = updatedHtml.replace(/<a\s+([^>]*)>(.*?)<\/a>/gi, (fullMatch, attrs, innerHtml) => {
      const cleanInner = innerHtml.replace(/<[^>]+>/g, '').replace(/&nbsp;|&#160;/gi, ' ').trim();
      const cleanOld = oldText.replace(/&nbsp;|&#160;/gi, ' ').trim();

      const urlMatches = oldUrl && attrs.toLowerCase().includes(oldUrl.toLowerCase());
      const textMatches = cleanOld && cleanInner.toLowerCase() === cleanOld.toLowerCase();

      if (urlMatches || textMatches) {
        matchCount++;
        console.log(`[rpcApplyGmailFix] Matched link #${matchCount}: "${fullMatch}". Replacing with: "<a ${attrs}>${newText}</a>"`);
        return `<a ${attrs}>${newText}</a>`;
      }
      return fullMatch;
    });

    console.log(`[rpcApplyGmailFix] Total anchor links replaced: ${matchCount}`);
  } else if (fixType === 'ALT_TEXT') {
    const targetIdx = parseInt(e.parameters['imgIdx'], 10) || 1;
    let suggestedAlt = e.parameters['suggestedAlt'] || '';

    if (!suggestedAlt || suggestedAlt.trim() === '') {
      console.log(`[rpcApplyGmailFix] Lazy AI Alt Text generation requested for Image #${targetIdx}...`);
      let base64Blob = '';
      if (inlineBlobs && inlineBlobs[targetIdx - 1]) {
        try {
          base64Blob = Utilities.base64Encode(inlineBlobs[targetIdx - 1].getBytes());
          console.log(`[rpcApplyGmailFix] Encoded inlineBlob #${targetIdx} for AI generation. Length: ${base64Blob.length}`);
        } catch (err) {
          console.warn(`[rpcApplyGmailFix] Failed to encode blob for Image #${targetIdx}:`, err);
        }
      }
      try {
        suggestedAlt = generateAiAltText(`gmail_img_${targetIdx}`, undefined, base64Blob);
        console.log(`[rpcApplyGmailFix] Successfully generated AI Alt Text: "${suggestedAlt}"`);
      } catch (err) {
        console.warn(`[rpcApplyGmailFix] Exception during lazy AI generation:`, err);
      }
      if (!suggestedAlt || suggestedAlt.trim() === '') {
        suggestedAlt = 'Visual photograph or graphic attachment';
      }
    }

    console.log(`[rpcApplyGmailFix] ALT_TEXT fix requested. Target image index: ${targetIdx}, Final alt: "${suggestedAlt}"`);

    let currIdx = 0;
    let matchCount = 0;
    updatedHtml = updatedHtml.replace(/<img\b([^>]*)>/gi, (fullMatch, attrs) => {
      currIdx++;
      if (currIdx === targetIdx) {
        matchCount++;
        console.log(`[rpcApplyGmailFix] Matched image #${currIdx}: "${fullMatch}".`);
        if (/alt=(?:["'][^"']*["']|[^\s>]+)/i.test(attrs)) {
          const newImg = fullMatch.replace(/alt=(?:["'][^"']*["']|[^\s>]+)/i, `alt="${suggestedAlt}"`);
          console.log(`[rpcApplyGmailFix] Replaced existing alt: "${newImg}"`);
          return newImg;
        } else {
          const newImg = `<img alt="${suggestedAlt}" ${attrs}>`;
          console.log(`[rpcApplyGmailFix] Added new alt attribute: "${newImg}"`);
          return newImg;
        }
      }
      return fullMatch;
    });

    console.log(`[rpcApplyGmailFix] Total images replaced: ${matchCount}`);
  } else if (fixType === 'MARK_DECORATIVE') {
    const targetIdx = parseInt(e.parameters['imgIdx'], 10) || 1;
    console.log(`[rpcApplyGmailFix] MARK_DECORATIVE fix requested for image #${targetIdx}`);
    let currIdx = 0;
    let matchCount = 0;
    updatedHtml = updatedHtml.replace(/<img\b([^>]*)>/gi, (fullMatch, attrs) => {
      currIdx++;
      if (currIdx === targetIdx) {
        matchCount++;
        if (/alt=(?:["'][^"']*["']|[^\s>]+)/i.test(attrs)) {
          return fullMatch.replace(/alt=(?:["'][^"']*["']|[^\s>]+)/i, 'alt=""');
        } else {
          return `<img alt="" ${attrs}>`;
        }
      }
      return fullMatch;
    });
    console.log(`[rpcApplyGmailFix] Image #${targetIdx} marked as decorative (alt=""). Replaced: ${matchCount}`);
  } else if (fixType === 'CUSTOM_ALT_TEXT') {
    const targetIdx = parseInt(e.parameters['imgIdx'], 10) || 1;
    const fieldName = `customAlt_${targetIdx}`;
    const userAlt = (e?.formInput?.[fieldName] || e?.formInputs?.[fieldName]?.[0] || '').trim();
    console.log(`[rpcApplyGmailFix] CUSTOM_ALT_TEXT fix requested for image #${targetIdx}. User typed: "${userAlt}"`);
    const finalAlt = userAlt || 'Visual photograph or graphic attachment';

    let currIdx = 0;
    let matchCount = 0;
    updatedHtml = updatedHtml.replace(/<img\b([^>]*)>/gi, (fullMatch, attrs) => {
      currIdx++;
      if (currIdx === targetIdx) {
        matchCount++;
        if (/alt=(?:["'][^"']*["']|[^\s>]+)/i.test(attrs)) {
          return fullMatch.replace(/alt=(?:["'][^"']*["']|[^\s>]+)/i, `alt="${finalAlt}"`);
        } else {
          return `<img alt="${finalAlt}" ${attrs}>`;
        }
      }
      return fullMatch;
    });
    console.log(`[rpcApplyGmailFix] Total images updated with custom alt text: ${matchCount}`);
  } else {
    // Universal text replacement handler for List Formatting, Color Contrast, Heading Structure, Table Structure, and Readable Typography
    const oldText = e.parameters['oldText'] || '';
    const newText = e.parameters['newText'] || '';
    if (oldText && newText) {
      updatedHtml = updatedHtml.replace(oldText, newText);
      if (fixType === 'List Formatting' || fixType === 'LIST') {
        updatedHtml = updatedHtml.replace(/<\/ul>\s*(?:<br\s*\/?>|\s)*<ul>/gi, '');
        updatedHtml = updatedHtml.replace(/<\/ol>\s*(?:<br\s*\/?>|\s)*<ol>/gi, '');
      }
      console.log(`[rpcApplyGmailFix] Replaced (${fixType}): "${oldText.substring(0, 30)}..." -> "${newText.substring(0, 30)}..."`);
    }
  }

/**
 * Converts any cid: or internal image src attributes in the HTML to inline base64 data URIs
 * using the fetched inline image attachment blobs. This ensures Gmail web compose can render the images
 * natively in the browser without broken image icons or attachment routing errors.
 */
/**
 * Safely updates the target draft on Gmail servers, ensuring every inline image blob is explicitly mapped
 * to a corresponding src="cid:..." attribute in the HTML body so attachments never break or get discarded.
 */
function syncServerDraftWithAttachments(targetDraft: any, updatedHtml: string, fixedCount: number): boolean {
  try {
    const msg = targetDraft.getMessage();
    const to = msg.getTo() || '';
    const subject = msg.getSubject() || '';
    const plainBody = msg.getPlainBody() || '';
    const finalHtml = updatedHtml;
    const options: any = { htmlBody: finalHtml };

    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] syncServerDraftWithAttachments START. Target draft ID: ${targetDraft.getId()}, Subject: "${subject}"`);

    // 1. Extract HTML Content-IDs from finalHtml (e.g. src="cid:ii_ms4xy1w40")
    const htmlCids: string[] = [];
    const cidRegex = /src=["']cid:([^"'\s>]+)["']/gi;
    let cidMatch: RegExpExecArray | null;
    while ((cidMatch = cidRegex.exec(finalHtml)) !== null) {
      const parsedCid = cidMatch[1].trim();
      if (!htmlCids.includes(parsedCid)) htmlCids.push(parsedCid);
    }
    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] Parsed Content-IDs from HTML:`, htmlCids);

    // 2. Fetch all message attachments natively via GmailApp (no UrlFetchApp permission risk)
    let allAtts: GoogleAppsScript.Base.Blob[] = [];
    try {
      allAtts = msg.getAttachments({ includeInlineImages: true, includeAttachments: true }) || [];
    } catch (e: any) {
      console.warn('[DEBUG_IMAGE_DIAGNOSTIC] Native getAttachments error:', e);
    }
    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] Native getAttachments returned ${allAtts.length} total attachment blobs.`);

    // 3. Attempt REST API CID mapping as an optional boost
    let restCidMap: Record<string, GoogleAppsScript.Base.Blob> = {};
    try {
      restCidMap = getInlineImageMapViaRest(msg.getId());
      console.log(`[DEBUG_IMAGE_DIAGNOSTIC] REST CID map keys:`, Object.keys(restCidMap));
    } catch (restErr: any) {
      console.warn('[DEBUG_IMAGE_DIAGNOSTIC] REST CID mapping skipped/failed:', restErr.message || restErr);
    }

    // 4. Build inlineImages map for options
    const inlineImagesMap: Record<string, GoogleAppsScript.Base.Blob> = {};

    const imageBlobs = allAtts.filter(b => b && (b.getContentType()?.toLowerCase().startsWith('image/') || /\.(jpg|jpeg|png|gif|bmp|webp|svg)$/i.test(b.getName())));
    const nonImageBlobs = allAtts.filter(b => b && !imageBlobs.includes(b));

    htmlCids.forEach((cidKey, idx) => {
      if (restCidMap[cidKey]) {
        inlineImagesMap[cidKey] = restCidMap[cidKey];
      } else if (idx < imageBlobs.length && imageBlobs[idx]) {
        inlineImagesMap[cidKey] = imageBlobs[idx];
      }
    });

    Object.keys(restCidMap).forEach(k => {
      if (!inlineImagesMap[k] && restCidMap[k]) {
        inlineImagesMap[k] = restCidMap[k];
      }
    });

    if (nonImageBlobs.length > 0) options.attachments = nonImageBlobs;
    if (Object.keys(inlineImagesMap).length > 0) options.inlineImages = inlineImagesMap;

    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] Final options.inlineImages keys:`, Object.keys(options.inlineImages || {}));

    targetDraft.update(to, subject, plainBody, options);
    console.log(`[DEBUG_IMAGE_DIAGNOSTIC] ✓ targetDraft.update() executed successfully! Inline images in options: ${Object.keys(options.inlineImages || {}).length}.`);
    return true;
  } catch (err: any) {
    console.error('[DEBUG_IMAGE_DIAGNOSTIC] Server draft update error:', err);
    return false;
  }
}

  console.log(`[rpcApplyGmailFix] Did HTML change? ${updatedHtml !== htmlBody}`);
  // 1. Perform safe server-side draft update preserving inline attachments via Content-ID mapping
  let serverSyncSuccess = true;
  if (true) {
    serverSyncSuccess = false;
    const targetDrafts: any[] = [];
    if (draftId && typeof GmailApp !== 'undefined') {
      try {
        const d = GmailApp.getDraft(draftId);
        if (d) targetDrafts.push(d);
      } catch (err) {}
    }
    if (targetDrafts.length === 0 && typeof GmailApp !== 'undefined') {
      try {
        const ds = GmailApp.getDrafts();
        if (ds && ds.length > 0) targetDrafts.push(ds[0]);
      } catch (err) {}
    }

    if (targetDrafts.length > 0) {
      serverSyncSuccess = syncServerDraftWithAttachments(targetDrafts[0], updatedHtml, 1);
    }
  }

  const notice = '✓ Fix applied successfully to your email draft!';

  if (source === 'COMPOSE') {
    if (fixType === 'ALT_TEXT') {
      const cards = buildGmailComposeCard(e, '✓ Image Alternative Text updated on server draft!');
      return CardService.newActionResponseBuilder()
        .setNavigation(CardService.newNavigation().updateCard(cards[0]))
        .build();
    }
    return CardService.newUpdateDraftActionResponseBuilder()
      .setUpdateDraftBodyAction(
        CardService.newUpdateDraftBodyAction()
          .addUpdateContent(updatedHtml, CardService.ContentType.MUTABLE_HTML)
          .setUpdateType(CardService.UpdateDraftBodyType.REPLACE)
      )
      .build();
  } else {
    const cards = buildGmailHomepageCard(e, notice);
    return CardService.newActionResponseBuilder()
      .setNavigation(CardService.newNavigation().updateCard(cards[0]))
      .build();
  }
}

/**
 * Applies all fixable accessibility issues (links, alt text, lists) in the active Gmail draft in a single step.
 */
export function rpcApplyAllGmailFixes(e: any): any {
  console.log('[rpcApplyAllGmailFixes] START. Triggered with event parameters:', JSON.stringify(e?.parameters || {}));
  const draftId = e?.parameters?.draftId;
  const source = e?.parameters?.source || 'COMPOSE';

  let { htmlBody, subject, draftId: resolvedId, inlineBlobs } = resolveDraftContent(e, true);
  let effectiveDraftId = draftId || resolvedId;

  if (!htmlBody) {
    const notice = '⚠️ Could not load active draft content to apply fixes.';
    const cards = source === 'HOMEPAGE' ? buildGmailHomepageCard(e, notice) : buildGmailComposeCard(e, notice);
    return CardService.newActionResponseBuilder()
      .setNavigation(CardService.newNavigation().updateCard(cards[0]))
      .build();
  }

  const issues = auditGmailDraftHtml(htmlBody, inlineBlobs);
  const fixableIssues = issues.filter(i => i.canAutoFix);
  console.log(`[rpcApplyAllGmailFixes] Found ${fixableIssues.length} fixable issues out of ${issues.length} total.`);

  let updatedHtml = htmlBody;
  let fixedCount = 0;

  // 1. Fix all text replacements (List Formatting, Color Contrast, Heading Structure, Table Structure, Readable Typography, and Links)
  for (const issue of fixableIssues) {
    if (issue.issueType === 'Alternative Text' || issue.issueType === 'ALT_TEXT') {
      continue; // Handled in step 2 below for image alt attributes
    }
    const oldText = (issue as any).oldText || '';
    const newText = (issue as any).newText || '';
    if (oldText && newText) {
      updatedHtml = updatedHtml.replace(oldText, newText);
      if (issue.issueType === 'List Formatting' || issue.issueType === 'LIST') {
        updatedHtml = updatedHtml.replace(/<\/ul>\s*(?:<br\s*\/?>|\s)*<ul>/gi, '');
        updatedHtml = updatedHtml.replace(/<\/ol>\s*(?:<br\s*\/?>|\s)*<ol>/gi, '');
      }
      fixedCount++;
      console.log(`[rpcApplyAllGmailFixes] Replaced (${issue.issueType}): "${oldText.substring(0, 30)}..." -> "${newText.substring(0, 30)}..."`);
    } else if (issue.issueType === 'Meaningful Hyperlinks' || issue.issueType === 'LINK') {
      const rawAnchor = (issue as any).rawAnchor || '';
      const suggestedText = (issue as any).suggestedText || '';
      if (rawAnchor && suggestedText) {
        updatedHtml = updatedHtml.replace(rawAnchor, suggestedText);
        fixedCount++;
        console.log(`[rpcApplyAllGmailFixes] Replaced LINK: "${rawAnchor}" -> "${suggestedText}"`);
      }
    }
  }

  // 2. Fix image alt text
  let currImgIdx = 0;
  const altIssues = fixableIssues.filter(i => i.issueType === 'Alternative Text' || i.issueType === 'ALT_TEXT');
  if (altIssues.length > 0) {
    const altMap: Record<number, string> = {};
    altIssues.forEach((i: any) => {
      altMap[i.imgIdx || 1] = i.suggestedAlt || 'Descriptive email graphic';
    });

    updatedHtml = updatedHtml.replace(/<img\b([^>]*)>/gi, (fullMatch, attrs) => {
      currImgIdx++;
      if (altMap[currImgIdx]) {
        fixedCount++;
        const suggestedAlt = altMap[currImgIdx];
        if (/alt=(?:["'][^"']*["']|[^\s>]+)/i.test(attrs)) {
          return fullMatch.replace(/alt=(?:["'][^"']*["']|[^\s>]+)/i, `alt="${suggestedAlt}"`);
        } else {
          return `<img alt="${suggestedAlt}" ${attrs}>`;
        }
      }
      return fullMatch;
    });
  }

  // 3. Update server draft preserving attachments and inline images
  let serverSyncSuccess = true;
  if (true) {
    serverSyncSuccess = false;
    const targetDrafts: any[] = [];
    if (effectiveDraftId && typeof GmailApp !== 'undefined') {
      try {
        const d = GmailApp.getDraft(effectiveDraftId);
        if (d) targetDrafts.push(d);
      } catch (err) {}
    }
    if (targetDrafts.length === 0 && typeof GmailApp !== 'undefined') {
      try {
        const ds = GmailApp.getDrafts();
        if (ds && ds.length > 0) targetDrafts.push(ds[0]);
      } catch (err) {}
    }

    if (targetDrafts.length > 0) {
      serverSyncSuccess = syncServerDraftWithAttachments(targetDrafts[0], updatedHtml, fixedCount);
    }
  }

  const notice = '✓ All accessibility fixes applied successfully to your email draft!';

  if (source === 'COMPOSE') {
    return CardService.newUpdateDraftActionResponseBuilder()
      .setUpdateDraftBodyAction(
        CardService.newUpdateDraftBodyAction()
          .addUpdateContent(updatedHtml, CardService.ContentType.MUTABLE_HTML)
          .setUpdateType(CardService.UpdateDraftBodyType.REPLACE)
      )
      .build();
  } else {
    const cards = buildGmailHomepageCard(e, notice);
    return CardService.newActionResponseBuilder()
      .setNavigation(CardService.newNavigation().updateCard(cards[0]))
      .build();
  }
}

/**
 * Checks if the user's active session requires OAuth scope authorization and triggers CardService AuthorizationException.
 */
function checkAuthorization(): void {
  if (typeof ScriptApp !== 'undefined' && typeof CardService !== 'undefined') {
    const authInfo = ScriptApp.getAuthorizationInfo(ScriptApp.AuthMode.FULL);
    if (authInfo && authInfo.getAuthorizationStatus() === ScriptApp.AuthorizationStatus.REQUIRED) {
      console.log('[checkAuthorization] Authorization required for updated scopes. Throwing AuthorizationException.');
      CardService.newAuthorizationException()
        .setAuthorizationUrl(authInfo.getAuthorizationUrl())
        .setResourceDisplayName('Google Workspace Accessibility Checker')
        .throwException();
    }
  }
}

/**
 * Builds native Google Workspace CardService UI for Gmail compose window toolbar.
 */
export function buildGmailComposeCard(e: any, noticeMsg?: string): GoogleAppsScript.Card_Service.Card[] {
  console.log('[buildGmailComposeCard] Triggered with event:', JSON.stringify(e || {}));
  checkAuthorization();
  const builder = CardService.newCardBuilder();
  builder.setHeader(CardService.newCardHeader().setTitle('Email Accessibility Checker'));

  const section = CardService.newCardSection();

  const demoAction = CardService.newAction()
    .setFunctionName('rpcPopulateGmailDemo')
    .setParameters({ source: 'COMPOSE' });
  section.addWidget(
    CardService.newTextButton()
      .setText('🧪 Reset Demo Email Draft')
      .setOnClickAction(demoAction)
  );

  if (noticeMsg && typeof noticeMsg === 'string') {
    section.addWidget(
      CardService.newTextParagraph().setText(`<font color="#0d652d"><b>${noticeMsg}</b></font>`)
    );
  }

  try {
    const { htmlBody, subject, draftId, inlineBlobs } = resolveDraftContent(e, true);

    if (htmlBody) {
      if (subject) {
        section.addWidget(CardService.newTextParagraph().setText(`<b>Draft:</b> ${subject}`));
      }
      const issues = auditGmailDraftHtml(htmlBody, inlineBlobs);

      if (issues.length === 0) {
        const textWidget = CardService.newTextParagraph().setText('<b>✓ All Clear!</b><br>No WCAG 2.1 Level AA link or image accessibility issues detected in your draft email.');
        section.addWidget(textWidget);
      } else {
        const headerWidget = CardService.newTextParagraph().setText(`<b>Found ${issues.length} Accessibility Issue(s)</b>`);
        section.addWidget(headerWidget);
        renderIssuesWithQuickFix(section, issues, draftId, 'COMPOSE');
      }
    } else {
      section.addWidget(
        CardService.newTextParagraph().setText(
          '<b>⚠️ No Active Draft Content Detected</b><br><br>' +
          'When invoked, the add-on checks for your active email draft. No saved draft body was found right now.<br><br>' +
          '<b>How to audit your email:</b><br>' +
          '1. Type a recipient, subject, or message body in the compose window.<br>' +
          '2. Wait ~2 seconds for Gmail to auto-save the draft to the server.<br>' +
          '3. Re-open or click check below.'
        )
      );
    }

    builder.addSection(section);
  } catch (err: any) {
    console.error('[buildGmailComposeCard] Error:', err);
    section.addWidget(CardService.newTextParagraph().setText(`Audit Error: ${err.message || err}`));
    builder.addSection(section);
  }

  return [builder.build()];
}

/**
 * Builds native Google Workspace CardService UI for Gmail homepage / right-hand sidebar.
 */
export function buildGmailHomepageCard(e: any, noticeMsg?: string): GoogleAppsScript.Card_Service.Card[] {
  console.log('[buildGmailHomepageCard] Triggered. NoticeMsg present:', !!noticeMsg);
  checkAuthorization();
  const builder = CardService.newCardBuilder();
  builder.setHeader(CardService.newCardHeader().setTitle('Email Accessibility Checker'));

  const section = CardService.newCardSection();

  const demoAction = CardService.newAction()
    .setFunctionName('rpcPopulateGmailDemo')
    .setParameters({ source: 'HOMEPAGE' });
  section.addWidget(
    CardService.newTextButton()
      .setText('🧪 Create Demo Email Draft')
      .setOnClickAction(demoAction)
  );

  if (noticeMsg && typeof noticeMsg === 'string') {
    section.addWidget(
      CardService.newTextParagraph().setText(`<font color="#0d652d"><b>${noticeMsg}</b></font>`)
    );
  }

  try {
    const { htmlBody, subject, draftId, inlineBlobs } = resolveDraftContent(e, false);

    if (htmlBody) {
      section.addWidget(
        CardService.newTextParagraph().setText(`<b>Checking Draft:</b> ${subject || '(Untitled Draft)'}`)
      );

      const refreshAction = CardService.newAction().setFunctionName('refreshGmailHomepageCard');
      section.addWidget(
        CardService.newTextButton()
          .setText('🔄 Refresh Audit')
          .setOnClickAction(refreshAction)
      );

      const issues = auditGmailDraftHtml(htmlBody, inlineBlobs);

      if (issues.length === 0) {
        section.addWidget(
          CardService.newTextParagraph().setText('<b>✓ All Clear!</b><br>No WCAG 2.1 Level AA link or image accessibility issues detected in your draft email.')
        );
      } else {
        section.addWidget(
          CardService.newTextParagraph().setText(`<b>Found ${issues.length} Accessibility Issue(s)</b>`)
        );
        renderIssuesWithQuickFix(section, issues, draftId, 'HOMEPAGE');
      }
    } else {
      section.addWidget(
        CardService.newTextParagraph().setText(
          '<b>Welcome to Google Workspace Accessibility Checker!</b><br><br>' +
          'This add-on scans your email drafts for WCAG 2.1 AA compliance and offers 1-click intelligent auto-remediation.<br><br>' +
          '<b>What We Check:</b><br>' +
          '• <b>Links:</b> Unclear anchor text & raw URLs<br>' +
          '• <b>Images:</b> Missing or generic alt text<br>' +
          '• <b>Contrast:</b> Low text contrast ratio<br>' +
          '• <b>Headings:</b> Non-semantic faux headings<br>' +
          '• <b>Tables:</b> Data tables missing headers<br>' +
          '• <b>Lists:</b> Simulated manual bullet lists<br>' +
          '• <b>Typography:</b> Small unreadable text sizes<br><br>' +
          '<b>How to Start:</b><br>' +
          'Open or compose an email in Gmail, and the checker will automatically scan your draft!'
        )
      );
      const checkAction = CardService.newAction().setFunctionName('rpcScanLatestDraft');
      section.addWidget(
        CardService.newTextButton()
          .setText('🔍 Scan Latest Saved Draft')
          .setOnClickAction(checkAction)
      );
    }

    builder.addSection(section);
  } catch (err: any) {
    console.error('[buildGmailHomepageCard] Error:', err);
    section.addWidget(CardService.newTextParagraph().setText(`Audit Error: ${err.message || err}`));
    builder.addSection(section);
  }

  return [builder.build()];
}

/**
 * Action handler for refreshing the homepage card without duplicating card stack.
 */
export function refreshGmailHomepageCard(e: any): GoogleAppsScript.Card_Service.ActionResponse {
  console.log('[refreshGmailHomepageCard] Triggered.');
  const cards = buildGmailHomepageCard(e);
  return CardService.newActionResponseBuilder()
    .setNavigation(CardService.newNavigation().updateCard(cards[0]))
    .build();
}

/**
 * Builds native Google Workspace CardService UI when viewing a received or sent email message.
 */
export function buildGmailMessageCard(e: any): GoogleAppsScript.Card_Service.Card[] {
  console.log('[buildGmailMessageCard] Triggered.');
  checkAuthorization();
  const builder = CardService.newCardBuilder();
  builder.setHeader(CardService.newCardHeader().setTitle('Email Accessibility Checker'));

  const section = CardService.newCardSection();

  try {
    const messageId = e?.gmail?.messageId || e?.messageMetadata?.messageId || e?.gmail?.messageMetadata?.messageId;
    let htmlBody = '';
    let msgSubject = '';
    let inlineBlobs: GoogleAppsScript.Base.Blob[] = [];

    if (messageId && typeof GmailApp !== 'undefined') {
      try {
        const msg = GmailApp.getMessageById(messageId);
        if (msg) {
          htmlBody = msg.getBody();
          msgSubject = msg.getSubject() || '(Untitled Message)';
          try { 
            const allAtts = msg.getAttachments({ includeInlineImages: true, includeAttachments: true }) || [];
            inlineBlobs = allAtts.filter(b => b && (b.getContentType()?.toLowerCase().startsWith('image/') || /\.(jpg|jpeg|png|gif|bmp|webp|svg)$/i.test(b.getName())));
          } catch (attErr) {}
        }
      } catch (err: any) {
        console.warn('[buildGmailMessageCard] Error fetching message by ID:', err);
      }
    }

    if (htmlBody) {
      section.addWidget(
        CardService.newTextParagraph().setText(`<b>Auditing Message:</b> ${msgSubject}`)
      );

      const issues = auditGmailDraftHtml(htmlBody, inlineBlobs);

      if (issues.length === 0) {
        section.addWidget(
          CardService.newTextParagraph().setText('<b>✓ All Clear!</b><br>No WCAG 2.1 Level AA link or image accessibility issues detected in this email.')
        );
      } else {
        section.addWidget(
          CardService.newTextParagraph().setText(`<b>Found ${issues.length} Accessibility Issue(s)</b>`)
        );
        issues.forEach((issue: any) => {
          const keyText = `<b>${issue.severity}</b>: ${issue.title}<br><i>${issue.description}</i>`;
          section.addWidget(CardService.newTextParagraph().setText(keyText));
        });
      }
    } else {
      section.addWidget(CardService.newTextParagraph().setText('Could not load email message content for auditing.'));
    }

    builder.addSection(section);
  } catch (err: any) {
    console.error('[buildGmailMessageCard] Error:', err);
    section.addWidget(CardService.newTextParagraph().setText(`Audit Error: ${err.message || err}`));
    builder.addSection(section);
  }

  return [builder.build()];
}

/**
 * Resettable test suite for Gmail composition: Populates the active draft with demo WCAG 2.1 AA violations.
 */
export function rpcPopulateGmailDemo(e: any): any {
  console.log('[rpcPopulateGmailDemo] START. Triggered with event:', JSON.stringify(e || {}));
  const source = e?.parameters?.source || 'COMPOSE';

  const demoHtml = `<div dir="ltr">
<div style="font-size: 18px; font-weight: bold; color: #1a73e8; margin-bottom: 12px;">Welcome to the Gmail Accessibility Audit Demo</div>
<div>This email draft contains intentional WCAG 2.1 AA violations across 7 comprehensive accessibility categories so you can test automated detection and 1-click remediation.</div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 1: Faux Headings</h3>
<div style="font-size: 16px; font-weight: bold;">Project Architecture Overview</div>
<div>Large bold text above looks like a heading but is a plain &lt;div&gt;, preventing screen reader navigation.</div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 2: Low Color Contrast</h3>
<div style="color: #a0a0a0;">This text is light gray (#a0a0a0) with a 2.1:1 contrast ratio against white, violating WCAG 4.5:1 minimums.</div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 3: Unclear Hyperlink Anchor Text</h3>
<div>To review the quarterly accessibility guidelines, please <a href="http://test.com" target="_blank">Click Here</a> or <a href="https://www.w3.org/WAI/" target="_blank">learn more</a>.</div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 4: Missing Image Alternative Text</h3>
<div>Here is the attached visual system diagram:</div>
<div><img src="https://www.gstatic.com/images/branding/product/2x/gmail_2020q4_48dp.png" alt="IMG_2068.JPG" width="96" height="96"></div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 5: Simulated Manual Bullet List</h3>
<div>Action items for next week:</div>
<div>- apples</div>
<div>- Oranges</div>
<div>- bananas</div>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 6: Data Table Missing Headers</h3>
<table border="1" cellpadding="6" style="border-collapse: collapse; width: 100%;">
  <tr><td>Feature</td><td>Status</td><td>Priority</td></tr>
  <tr><td>Contrast Check</td><td>Complete</td><td>High</td></tr>
  <tr><td>Screen Reader</td><td>In Progress</td><td>Medium</td></tr>
</table>
<br>
<h3 style="font-size: 14px; font-weight: bold; color: #3c4043; margin-top: 16px; margin-bottom: 4px;">Test Case 7: Small Unreadable Typography</h3>
<div style="font-size: 9px; color: #5f6368;">Confidentiality Notice: This fine print disclaimer text is 9px, violating readable typography size guidelines.</div>
<br>
<div>End of demo draft. Click "&#x1F504; Re-check Current Draft" in the sidebar to scan!</div>
</div>`;

  if (source === 'COMPOSE') {
    return CardService.newUpdateDraftActionResponseBuilder()
      .setUpdateDraftBodyAction(
        CardService.newUpdateDraftBodyAction()
          .addUpdateContent(demoHtml, CardService.ContentType.MUTABLE_HTML)
          .setUpdateType(CardService.UpdateDraftBodyType.REPLACE)
      )
      .build();
  } else {
    let newDraftId = '';
    let lastErrMsg = '';
    if (typeof GmailApp !== 'undefined') {
      const subject = 'Accessibility Audit Demo Draft (WCAG Test Suite)';
      let recipient = '';
      try {
        const userEmail = Session.getActiveUser().getEmail();
        if (userEmail) recipient = userEmail;
      } catch (emailErr: any) {
        console.warn('[rpcPopulateGmailDemo] Could not get active user email (userinfo scope not granted):', emailErr);
      }

      try {
        console.log('[rpcPopulateGmailDemo] Attempting GmailApp.createDraft with recipient:', recipient || '(empty string)');
        const d = GmailApp.createDraft(recipient, subject, 'Please open in HTML view.', {
          htmlBody: demoHtml
        });
        if (d) newDraftId = d.getId();
      } catch (err1: any) {
        console.warn('[rpcPopulateGmailDemo] First createDraft attempt failed:', err1);
        lastErrMsg = err1.message || String(err1);
        try {
          console.log('[rpcPopulateGmailDemo] Retrying createDraft with fallback demo@example.com...');
          const d2 = GmailApp.createDraft('demo@example.com', subject, 'Please open in HTML view.', {
            htmlBody: demoHtml
          });
          if (d2) newDraftId = d2.getId();
        } catch (err2: any) {
          console.error('[rpcPopulateGmailDemo] Second createDraft attempt failed:', err2);
          lastErrMsg = err2.message || String(err2);
        }
      }
    }

    const notice = newDraftId
      ? '✓ Created a new Demo Test Draft in your Gmail Drafts folder! Open your Drafts folder to test it!'
      : `⚠️ Could not create demo draft: ${lastErrMsg || 'Unknown Apps Script error'}`;

    const cards = buildGmailHomepageCard(e, notice);
    return CardService.newActionResponseBuilder()
      .setNavigation(CardService.newNavigation().updateCard(cards[0]))
      .build();
  }
}

/**
 * Action handler to explicitly scan the latest saved draft when invoked from the homepage dashboard.
 */
export function rpcScanLatestDraft(e: any): GoogleAppsScript.Card_Service.ActionResponse {
  console.log('[rpcScanLatestDraft] Triggered. Explicitly scanning latest draft.');
  const { htmlBody, subject, draftId } = resolveDraftContent(e, true);
  if (!htmlBody) {
    const cards = buildGmailHomepageCard(e, '⚠️ No saved drafts found in your Gmail account.');
    return CardService.newActionResponseBuilder()
      .setNavigation(CardService.newNavigation().updateCard(cards[0]))
      .build();
  }
  const fakeE = { ...e, draftId: draftId, draftMetadata: { id: draftId } };
  const cards = buildGmailHomepageCard(fakeE);
  return CardService.newActionResponseBuilder()
    .setNavigation(CardService.newNavigation().updateCard(cards[0]))
    .build();
}
